spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/confectionary
    username: admin
    password: admin
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
